# Configuration for the cluster that will perform the training
# in Google Cloud AI Platform with GPUs
# This configuration file allows for specifying training hyperparameters
# for model selection

# Example:
# Configure a master worker with 2 K80 GPUs

trainingInput:
  scaleTier: CUSTOM
  masterType: n1-highmem-8
  masterConfig:
    acceleratorConfig:
      count: 1
      type: NVIDIA_TESLA_K80
  hyperparameters:
    maxTrials: 8
    maxParallelTrials: 2
    enableTrialEarlyStopping: True
    goal: MINIMIZE
    hyperparameterMetricTag: loss_valid
    params:
    - parameterName: size-kernel
      type: DISCRETE
      discreteValues:
      - 3
      - 6
      - 9
    - parameterName: num-layers
      type: DISCRETE
      discreteValues:
      - 3
      - 6
      - 9
    - parameterName: len-seq
      type: DISCRETE
      discreteValues:
      - 1600
      - 2000
      - 4000
    - parameterName: size-batch
      type: DISCRETE
      discreteValues:
      - 100
      - 200
      - 400
    - parameterName: num-hidden
      type: DISCRETE
      discreteValues:
      - 150
      - 300
      - 600
    - parameterName: lr
      type: DOUBLE
      scaleType: UNIT_LINEAR_SCALE
      minValue: 0.00001
      maxValue: 0.001
    - parameterName: dropout
      type: DOUBLE
      scaleType: UNIT_LINEAR_SCALE
      minValue: 0.2
      maxValue: 0.5
